### ISSUE TITLE
Agent for Series?

### ISSUE THREAD

**Issue by 3l4d3** [sander1/YouTube-Agent.bundle#13]
This seem to only work with Movies.

I would rather have youtube channels sorted by Seres/channel/Season 1/All episodes.
Because I have used youtube-dl and gotten 167 videos.

Can this be done?

**Comment by ZeroQI** [comment]
I did a YouTube movie and TV Series agent here: https://github.com/ZeroQI/YouTube-Agent.bundle
Use my absolute series scanner beta branch to go with it
if you do [PLxxxxxx] or [youtube-xxxxxx] on the series folder name it should pull up all info.
