### ISSUE TITLE
Adding youtube channel name to metadata for filtering

### ISSUE THREAD

**Issue by ankenyr** [sander1/YouTube-Agent.bundle#5]
It would be nice to be able to filter by the channel name.
https://www.youtube.com/user/CGPGrey
Given this channel all videos would have "CGPGrey" in their metadata so one could filter based on the creator.

**Comment by sander1** [comment]
Which metadata field could we use for this? There isn't really a field for this. I guess adding username as "director" fits best?

**Comment by ankenyr** [comment]
I would use director, studio, or collections.

**Comment by sander1** [comment]
This has been added (https://github.com/sander1/YouTube-Agent.bundle/compare/76dee4c4a2089e0f1e26550a8c8d500f6f86ed5e...fe863ecb760616e59acf00d7b61069f9cbf2fe90). You have to enable the option in the agent's preferences...

![screen shot 2017-02-03 at 20 42 35](https://cloud.githubusercontent.com/assets/104684/22605708/620b044c-ea51-11e6-9ec2-10ea87676c08.jpg)

...and refresh the contents of your existing YouTube agent library.

**Comment by ankenyr** [comment]
Thank you!
